"""Création des tables

Revision ID: 8e99b2808c7d
Revises: 
Create Date: 2026-05-14 14:30:46.312797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e99b2808c7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comptable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveillant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterePaiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('idPromotion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPromotion'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etudiant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('postnom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('idPromotion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPromotion'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('preuvePaiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheminCapture', sa.Text(), nullable=False),
    sa.Column('statutValidation', sa.Boolean(), nullable=True),
    sa.Column('motifRejet', sa.Text(), nullable=True),
    sa.Column('idEtudiant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEtudiant'], ['etudiant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preuvePaiement')
    op.drop_table('etudiant')
    op.drop_table('criterePaiement')
    op.drop_table('surveillant')
    op.drop_table('promotion')
    op.drop_table('comptable')
    # ### end Alembic commands ###
