"""ajouts des champs dans la table comptable

Revision ID: 9ca9e6b42420
Revises: 8e99b2808c7d
Create Date: 2026-05-18 13:48:35.079175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ca9e6b42420'
down_revision = '8e99b2808c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterePaiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('idPromotion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPromotion'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preuvePaiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheminCapture', sa.Text(), nullable=False),
    sa.Column('statutValidation', sa.Boolean(), nullable=True),
    sa.Column('motifRejet', sa.Text(), nullable=True),
    sa.Column('idEtudiant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEtudiant'], ['etudiant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('preuvepaiement')
    op.drop_table('criterepaiement')
    with op.batch_alter_table('comptable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('prenom', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comptable', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('prenom')
        batch_op.drop_column('nom')

    op.create_table('criterepaiement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('montant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('session', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('idPromotion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idPromotion'], ['promotion.id'], name=op.f('criterepaiement_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('preuvepaiement',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cheminCapture', mysql.TEXT(), nullable=False),
    sa.Column('statutValidation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('motifRejet', mysql.TEXT(), nullable=True),
    sa.Column('idEtudiant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idEtudiant'], ['etudiant.id'], name=op.f('preuvepaiement_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('preuvePaiement')
    op.drop_table('criterePaiement')
    # ### end Alembic commands ###
