"""ajouts

Revision ID: d8086c2aec63
Revises: 2ea77a22c24a
Create Date: 2026-05-18 13:56:10.902412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8086c2aec63'
down_revision = '2ea77a22c24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterePaiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('idPromotion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idPromotion'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preuvePaiement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cheminCapture', sa.Text(), nullable=False),
    sa.Column('statutValidation', sa.Boolean(), nullable=True),
    sa.Column('motifRejet', sa.Text(), nullable=True),
    sa.Column('idEtudiant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEtudiant'], ['etudiant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preuvePaiement')
    op.drop_table('criterePaiement')
    # ### end Alembic commands ###
